### PR TITLE
AWS Lambda Example (Node.js)

### PR DESCRIPTION
**Pull request by PonomareVlad**
Tested using [AWS SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html)

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
Nice

**Comment by PonomareVlad** [comment]
@KnorpelSenf this is not completely tested yet, I'm [waiting for feedback](https://t.me/grammyjs/179043)

**Comment by KnorpelSenf** [comment]
I did not read the chat at that point, I just read that it's tested. I guess we can just open a follow-up PQ if there are things to fix.

I'm rather fast at merging example bots, I wouldn't do this with code that breaks production systems, but if you want to prevent early merges in the future, add a sentence to the pull request description, or apply draft state.

**Comment by PonomareVlad** [comment]
@KnorpelSenf Of course, no problem, I also think it's ready for merger, but I was hoping to get feedback earlier 😀

**Pull request merged**
