### PR TITLE
Reformat files

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
This is a repo with examples for Node.js. Doesn't it make more sense to stick with Node tooling then?

**Comment by roj1512** [comment]
Does Node have a formatting "tooling"?

**Comment by roj1512** [comment]
It doesn't matter which tool we use, I want to keep them formatted for consistency because right now some places are using single quotes and the rest is using double quotes.

**Comment by roj1512** [comment]
I also believe that Prettier will have a similar result, too.

**Comment by KnorpelSenf** [comment]
Prettier is set up for this repo, it just needs to be applied correctly.

**Comment by Loskir** [comment]
> some places are using single quotes and the rest is using double quotes.

and there’s kinda nothing wrong with it

**Comment by roj1512** [comment]
I'll use it to format everywhere except the Deno Deploy, will this be okay?

**Comment by Loskir** [comment]
Supabase also uses deno tooling for example

**Comment by roj1512** [comment]
I'll exclude that, too.

**Comment by Loskir** [comment]
Oh no, not tab width 4

**Comment by roj1512** [comment]
Tab width will be decided by KnorpelSenf's formatting GmBH.

**Review by KnorpelSenf — APPROVED** [review]
Rubber-stamp LGTM

**Comment by KnorpelSenf** [comment]
> Oh no, not tab width 4

I don't have too strong opinions about this

1. Make a point why one is better than the other or vice versa 
2. Submit a PQ
3. Party

**Pull request merged**
